config/routes.rb
Simi::Application.routes.draw do

  resources :empresas
  resources :equipes
  resources :funcionarios
  resources :localizacaos

  root 'home#index'

  

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	validates_presence_of :razao_social, :cnpj, :telefone, :endereco

	has_many :equipes
end

app/models/equipe.rb
class Equipe < ActiveRecord::Base
	validates_presence_of :nome

	belongs_to :empresa
	has_many :funcionarios

	scope :from, ->(empresa) {where(empresa: empresa)}
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
	validates_presence_of :nome, :numero_linha

	has_many :localizacaos
	belongs_to :equipe

	def self.from(empresa)
		equipes = empresa.equipes
		self.where(equipe_id: equipes)
	end
end

app/models/localizacao.rb
class Localizacao < ActiveRecord::Base
	validates_presence_of :latitude, :longitude

	belongs_to :funcionario

	def self.from(empresa)
		localizacoes_ordenadas = self.ordena_por_created_at_localizacao(Funcionario.from(empresa))

		self.agrupa_por_funcionario(localizacoes_ordenadas)
	end

	def ==(outra_localizacao)
		self.funcionario.id == outra_localizacao.funcionario.id
	end

	private

	def self.com_funcionario
		self.joins(:funcionario).includes(:funcionario)
	end

	def self.agrupa_por_funcionario(localizacoes_ordenadas)
		localizacoes_agrupadas = []
		localizacoes_ordenadas.each do |position|
			localizacoes_agrupadas<< position	unless localizacoes_agrupadas.include? position
		end
		localizacoes_agrupadas
	end

	def self.ordena_por_created_at_localizacao(funcionarios)
		self.com_funcionario.
				where(funcionario_id: funcionarios).
						order('localizacaos.created_at DESC')
	end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
	 before_action :set_empresa, only: [:show, :edit, :update, :destroy]

	def index
		@empresas = Empresa.all
		respond_with @empresas
	end

	def new
		@empresa = Empresa.new
		respond_with @empresa
	end

	def create
		@empresa = Empresa.new(empresa_params)

		@empresa.save
		respond_with @empresa
	end

	def show
		respond_with @empresa
	end

	def edit
		respond_with @empresa
	end

	def update
		@empresa.update(empresa_params)
		respond_with @empresa
	end

	def destroy
		@empresa.destroy
		respond_with @empresa
	end

	private

	def empresa_params
		params.
			require(:empresa).
			permit(:razao_social, :telefone, :cnpj, :endereco)
	end

	def set_empresa
    @empresa = Empresa.find(params[:id])
  end
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
	before_action :set_equipe, only: [:show, :edit, :update, :destroy]

	def index
	#LISTAR SOMENTE AS EQUIPES DO USUARIO CORRENTE
		@equipes = Equipe.from(Empresa.first)
		respond_with @equipes
	end

	def new
		@equipe = Equipe.new
		respond_with @equipe
	end

	def create
		@equipe = Equipe.new(equipe_params)
		#SETAR EMPRESA DO USUARIO CORRENTE
		@equipe.empresa = Empresa.first
		@equipe.save
		respond_with @equipe
	end

	def edit
		respond_with @equipe
	end

	def update
		@equipe.update(equipe_params)
		respond_with @equipe
	end

	def destroy
		@equipe.destroy
		respond_with @equipe
	end

	def show
		respond_with @equipe
	end

	private

	def equipe_params
		params.
			require(:equipe).permit(:nome)
	end

	def set_equipe
			#LISTAR SOMENTE AS EQUIPES DO USUARIO CORRENTE
		@equipe = Equipe.find(params[:id])
	end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
	before_action	:set_funcionario, only: [:update,:edit,:destroy, :show]

	def index
		@funcionarios = Funcionario.from(Empresa.first)
		respond_with @funcionarios
	end

	def new
		@funcionario = Funcionario.new
		respond_with @funcionario
	end

	def create
		@funcionario = Funcionario.new(funcionario_params)
		@funcionario.save
		respond_with @funcionario
	end

	def edit
		respond_with @funcionario
	end

	def show
		respond_with @funcionario
	end

	def update
		@funcionario.update(funcionario_params)
		respond_with @funcionario
	end

	def destroy
		@funcionario.destroy
		respond_with @funcionario
	end

	private

	def set_funcionario
		@funcionario = Funcionario.find(params[:id])	
	end

	def funcionario_params 
		params.
			require(:funcionario).
			permit(:nome, :numero_linha, :equipe_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/localizacaos_controller.rb
class LocalizacaosController < ApplicationController
	before_action :set_localizacao, only: [:destroy, :update, :edit, :show]

	def index
		@localizacoes = Localizacao.from(Empresa.first)
		respond_to do |format|
			format.js {render json: @localizacoes,:include => :funcionario }
		end
	end

	def new
		@localizacao = Localizacao.new
		respond_with @localizacao
	end

	def create
		@localizacao = Localizacao.new(localizacao_params)
		@localizacao.funcionario=Funcionario.first
		@localizacao.save
		respond_with @localizacao
	end

	def edit
		respond_with @localizacao
	end

	def update
		@localizacao.update(localizacao_params)
		respond_with @localizacao
	end

	def show
		respond_with @localizacao
	end

	def destroy
		@localizacao.destroy
		respond_with @localizacao
	end


	private

	def localizacao_params
		params.
			require(:localizacao).
				permit(:latitude, :longitude)
	end

	def set_localizacao
		@localizacao = Localizacao.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag(
			:div,
			model.errors[attribute].first,
			class: 'error_message'
			)
		end
	end

	def google_maps_api
    content_tag(:script,:type => "text/javascript",:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyC7aAo5T7TgqVJCef01j2rthZoCFMx2i4o&sensor=false") do
    end
  end

end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/localizacaos_helper.rb
module LocalizacaosHelper
end

app/views/empresas/_form.html.erb
<%= form_for @empresa do |f|%>

	<p>
		<%= f.label :razao_social %>
		<%= f.text_field :razao_social %>
		<%= error_tag @empresa, :razao_social %>
	</p>

	<p>
		<%= f.label :cnpj %>
		<%= f.text_field :cnpj %>
		<%= error_tag @empresa, :cnpj %>
	</p>

	<p>
		<%= f.label :telefone %>
		<%= f.text_field :telefone %>
		<%= error_tag @empresa, :telefone %>
	</p>

	<p>
		<%= f.label :endereco %>
		<%= f.text_field :endereco %>
		<%= error_tag @empresa, :endereco %>
	</p>

	<div class="form-actions">
		<%= f.submit class: "btn btn-info" %>
	</div>
	
<% end %>

app/views/empresas/edit.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

			<%= render 'form' %>

	</fieldset>

	<%= link_to t('links.back'), root_path, class: "btn"  %>

</div>

app/views/empresas/index.html.erb
<div class="span12 white padding">

  <fieldset>
    <legend><%= t'.titulo' %></legend>

    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t'.razao_social' %></th>
          <th><%= t'.cnpj' %></th>
          <th><%= t'.telefone' %></th>
          <th><%= t'.endereco' %></th>
          <th><%= t'table.show' %></th>
          <th><%= t'table.edit' %></th>
          <th><%= t'table.delete' %></th>
        </tr>
      </thead>

      <tbody>
        <% @empresas.each do |empresa| %>
          <tr>
            <td><%= empresa.razao_social %></td>
            <td><%= empresa.cnpj %></td>
            <td><%= empresa.telefone %></td>
            <td><%= empresa.endereco %></td>
            <td><%= link_to image_tag("/imgs/icons/show_icon.png"), empresa %></td>
            <td><%= link_to image_tag("/imgs/icons/edit_icon.png"), edit_empresa_path(empresa) %></td>
            <td><%= link_to image_tag("/imgs/icons/delete_icon2.png"), empresa, method: :delete, data: { confirm: t('message.are_you_sure') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </fieldset>

<%= link_to t('links.new_empresa'), new_empresa_path, class: "btn" %>
</div>

app/views/empresas/new.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

			<%= render 'form' %>

	</fieldset>

			<%= link_to t('links.back'), root_path, class: "btn"  %>
</div>

app/views/empresas/show.html.erb
<p><%= t '.razao_social', razao_social: @empresa.razao_social %></p>
<p><%= t '.cnpj', cnpj: @empresa.cnpj %></p>
<p><%= t '.telefone', telefone: @empresa.telefone %> </p>
<p><%= t '.endereco', endereco: @empresa.endereco %></p>

<%= link_to t('links.edit'), edit_empresa_path(@empresa) %>
<%= link_to t('links.list_empresas'), empresas_path %>

app/views/equipes/_form.html.erb
<%= form_for @equipe do |f| %>

	<p>
		<%= f.label :nome %>
		<%= f.text_field :nome %>
		<%= error_tag @equipe, :nome %>
	</p>

	<div class="form-actions">
		<%= f.submit class: "btn btn-info" %>
	</div>

<% end %>

app/views/equipes/edit.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

			<%= render 'form' %>

	</fieldset>

	<%= link_to t('links.back'), equipes_path, class: "btn"  %>

</div>

app/views/equipes/index.html.erb
<div class="span12 white padding">

  <fieldset>
    <legend><%= t'.titulo' %></legend>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t'.nome' %></th>
        <th><%= t'table.show' %></th>
        <th><%= t'table.edit' %></th>
        <th><%= t'table.delete' %></th>
      </tr>
    </thead>

    <tbody>
      <% @equipes.each do |equipe| %>
        <tr>
          <td><%= equipe.nome %></td>
          <td><%= link_to image_tag("/imgs/icons/show_icon.png"), equipe %></td>
          <td><%= link_to image_tag("/imgs/icons/edit_icon.png"), edit_equipe_path(equipe) %></td>
          <td><%= link_to image_tag("/imgs/icons/delete_icon2.png"), equipe, method: :delete, data: { confirm: t('message.are_you_sure') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</fieldset>

<%= link_to t('links.new_equipe'), new_equipe_path, class: "btn" %>

</div>

app/views/equipes/new.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

			<%= render 'form' %>

	</fieldset>

		<%= link_to t('links.back'), equipes_path, class: "btn"  %>

</div>

app/views/equipes/show.html.erb
<p><%= t '.nome', nome: @equipe.nome %></p>

<%= link_to t('links.edit'), edit_equipe_path(@equipe) %>
<%= link_to t('links.list_equipes'), equipes_path %>

app/views/funcionarios/_form.html.erb
<%= form_for @funcionario do |f| %>

	<p>
		<%= f.label :nome %>
		<%= f.text_field :nome %>
		<%= error_tag @funcionario, :nome %>
	</p>

	<p>
		<%= f.label :numero_linha %>
		<%= f.text_field :numero_linha %>
		<%= error_tag @funcionario, :numero_linha %>
	</p>	

	<p>
		<%= f.label :equipe %>
		<%= f.select :equipe_id, Equipe.from(Empresa.first).map {|equipe| [equipe.nome, equipe.id]} %>
		<%= error_tag @funcionario, :equipe %>
	</p>
	<div class="form-actions">
		<%= f.submit class: "btn btn-info" %>
	</div>

<% end %>

app/views/funcionarios/edit.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

		<%= render 'form' %>

	</fieldset>

		<%= link_to t('links.back'), funcionarios_path, class: "btn"  %>

</div>

app/views/funcionarios/index.html.erb
<div class="span12 white padding">

  <fieldset>
    <legend><%= t'.titulo' %></legend>

    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t'.nome' %></th>
          <th><%= t'.numero_linha' %></th>
          <th><%= t'table.show' %></th>
          <th><%= t'table.edit' %></th>
          <th><%= t'table.delete' %></th>
        </tr>
      </thead>

      <tbody>
        <% @funcionarios.each do |funcionario| %>
          <tr>
            <td><%= funcionario.nome %></td>
            <td><%= funcionario.numero_linha %></td>
            <td><%= link_to image_tag("/imgs/icons/show_icon.png"), funcionario %></td>
            <td><%= link_to image_tag("/imgs/icons/edit_icon.png"), edit_funcionario_path(funcionario) %></td>
            <td><%= link_to image_tag("/imgs/icons/delete_icon2.png"), funcionario, method: :delete, data: { confirm: t('message.are_you_sure') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>

  <%= link_to t('links.new_funcionario'), new_funcionario_path, class: "btn" %>

</div>

app/views/funcionarios/new.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

	<%= render 'form' %>

	</fieldset>

	<%= link_to t('links.back'), funcionarios_path, class: "btn" %>

</div>

app/views/funcionarios/show.html.erb
<p><%= t '.nome', nome: @funcionario.nome %></p>
<p><%= t '.numero_linha', numero_linha: @funcionario.numero_linha %></p>

<%= link_to t('links.edit'), edit_funcionario_path(@funcionario) %>
<%= link_to t('links.list_funcionarios'), funcionarios_path %>

app/views/home/index.html.erb
<!--MAP content-->
<div class="span12 border">

	<div id="map-canvas" style="height: 500px; width: 100%">

	</div>


</div>
<!-- FIM MAP -->

app/views/layouts/_header.html.erb
<!-- NAVBAR -->
<div class="navbar"> 
	<div class="navbar-inner">

		<div class="container">
			<div class="row-fluid">

				<div class="span4">
					<div class="span3 center">
      			<%= link_to image_tag("/imgs/location-icon.png"), root_path, :class =>"brand" %>
      		</div>

      		<div class="span6 ">
      			<div class="brand center">
      				<h4 class="color-title">SISTEMAS DE MONITORAMENTO</h4>
      			</div>
      		</div>
    		</div>

    		<div class="span8 ">
    			<div class="span12 brand ">
						<form class="navbar-form ">
						  <input type="text" class="span8" placeholder="digite o nome do funcionário"> 
						  <button type="submit" class="btn">Buscar</button>
						</form>
					</div>
    		</div>

    	</div>
		</div>

	</div>
</div>
<!-- FIM NAVBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- Maps API Javascript -->
  <%= google_maps_api %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
 
<div class="container-fluid back-color-panel border">
	<!-- ROW -->
	<div class="row-fluid  margin">

		<div class="span12 ">
			
			<% if flash[:notice].present? %>
				<div class="alert alert-success">
					<p id="notice"><%= flash[:notice] %> </p>
				</div>
			<% end %>
				
			<% if alert.present? %>
				<div class="alert alert-danger">
					<p id="alert"><%= alert %> </p>
				</div>
			<% end %>


			<%= yield %>

		</div>

	</div>
	<!-- FIM ROW -->	

</div>

<div class="footer">2013 Todos os direitos reservados.</div>

</body>
</html>

app/views/localizacaos/_form.html.erb
<%= form_for @localizacao do |f| %>

	<p>
		<%= f.label :latitude %>
		<%= f.text_field :latitude %>
		<%= error_tag @localizacao, :latitude %>
	</p>

	<p>
		<%= f.label :longitude %>
		<%= f.text_field :longitude %>
		<%= error_tag @localizacao, :longitude %>
	</p>	
	
	<div class="form-actions">
		<%= f.submit class: "btn btn-info" %>
	</div>

<% end %>

app/views/localizacaos/edit.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

			<%= render 'form' %>

	</fieldset>

	<%= link_to t('links.back'), localizacaos_path, class: "btn"  %>

</div>

app/views/localizacaos/index.html.erb
<h1><%= t'.titulo' %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t'.latitude' %></th>
      <th><%= t'.longitude' %></th>
      <th><%= t'table.show' %></th>
      <th><%= t'table.edit' %></th>
      <th><%= t'table.delete' %></th>
    </tr>
  </thead>

  <tbody>
    <% @localizacoes.each do |localizacao| %>
      <tr>
        <td><%= localizacao.latitude %></td>
        <td><%= localizacao.longitude %></td>
        <td><%= link_to t('links.show'), localizacao %></td>
        <td><%= link_to t('links.edit'), edit_localizacao_path(localizacao) %></td>
        <td><%= link_to t('links.delete'), localizacao, method: :delete, data: { confirm: t('message.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new_localizacao'), new_localizacao_path %>

app/views/localizacaos/new.html.erb
<div class="span8 white padding">

	<fieldset>
	  <legend><%= t '.title' %></legend>

			<%= render 'form' %>

	</fieldset>

	<%= link_to t('links.back'), localizacaos_path, class: "btn"  %>

</div>

app/views/localizacaos/show.html.erb
<p><%= t '.latitude', latitude: @localizacao.latitude %></p>
<p><%= t '.longitude', longitude: @localizacao.longitude %></p>

<%= link_to t('links.edit'), edit_localizacao_path(@localizacao) %>
<%= link_to t('links.list_localizacaos'), localizacaos_path %>